export const data = {
  "hitkashrut.pdf": [
    {
      x: 430,
      y: 630,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "fullname",
    },
    {
      x: 430,
      y: 160,
      width: 200,
      height: 12,
      istext: true,
      page: 1,
      field_type: "sign",
    },
    {
      x: 230,
      y: 160,
      width: 200,
      height: 12,
      istext: true,
      page: 1,
      field_type: "r_sign",
    },
  ],
  "sodiut1.pdf": [
    {
      x: 330,
      y: 660,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "fullname",
    },
    {
      x: 190,
      y: 660,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "id",
    },
    {
      x: 400,
      y: 400,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "r_fullname",
    },
    {
      x: 190,
      y: 400,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "r_id",
    },
    {
      x: 310,
      y: 340,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "r_phone",
    },
    {
      x: 400,
      y: 210,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "date",
    },
    {
      x: 150,
      y: 180,
      width: 200,
      height: 12,
      istext: false,
      page: 0,
      field_type: "sign",
    },
  ],
  "sodiut2.pdf": [
    {
      x: 400,
      y: 540,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "fullname",
    },
    {
      x: 180,
      y: 540,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "id",
    },
    {
      x: 300,
      y: 502,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "shikum",
    },
    {
      x: 190,
      y: 485,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "tipul",
    },
    {
      x: 190,
      y: 468,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "company",
    },
    {
      x: 470,
      y: 280,
      width: 200,
      height: 12,
      istext: true,
      page: 0,
      field_type: "date",
    },
    {
      x: 240,
      y: 235,
      width: 48,
      height: 12,
      istext: false,
      page: 0,
      field_type: "sign",
    },
  ],
  "hitnadvut.pdf": [
    {
      x: 472,
      y: 675,
      width: 200,
      height: 11,
      istext: true,
      page: 0,
      field_type: "id",
    },
    {
      x: 325,
      y: 675,
      width: 200,
      height: 11,
      istext: true,
      page: 0,
      field_type: "firstname",
    },
    {
      x: 400,
      y: 675,
      width: 200,
      height: 11,
      istext: true,
      page: 0,
      field_type: "lastname",
    },
    {
      x: 240,
      y: 675,
      width: 200,
      height: 11,
      istext: true,
      page: 0,
      field_type: "address",
    },
    {
      x: 128,
      y: 680,
      width: 200,
      height: 10,
      istext: true,
      page: 0,
      field_type: "phone",
    },
    {
      x: 200,
      y: 485,
      width: 200,
      height: 10,
      istext: true,
      page: 0,
      field_type: "duration",
    },
    {
      x: 460,
      y: 215,
      width: 200,
      height: 10,
      istext: true,
      page: 0,
      field_type: "date",
    },
    {
      x: 120,
      y: 185,
      width: 48,
      height: 50,
      istext: false,
      page: 0,
      field_type: "sign",
    },
    {
      x: 450,
      y: 145,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "date",
    },
    {
      x: 380,
      y: 150,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "r_id",
    },
    {
      x: 320,
      y: 150,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "r_fullname",
    },
    {
      x: 240,
      y: 150,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "r_job",
    },
    {
      x: 120,
      y: 110,
      width: 48,
      height: 50,
      istext: false,
      page: 0,
      field_type: "sign",
    },
  ],
  "sodiut31.pdf": [
    {
      x: 450,
      y: 665,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "id",
    },
    {
      x: 305,
      y: 665,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "firstname",
    },
    {
      x: 380,
      y: 665,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "lastname",
    },
    {
      x: 210,
      y: 665,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "address",
    },
    {
      x: 115,
      y: 670,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "phone",
    },
    {
      x: 460,
      y: 215,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "date",
    },
    {
      x: 370,
      y: 220,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "fullname",
    },
    {
      x: 280,
      y: 220,
      width: 200,
      height: 9,
      istext: true,
      page: 0,
      field_type: "id",
    },
    {
      x: 110,
      y: 180,
      width: 70,
      height: 70,
      istext: false,
      page: 0,
      field_type: "sign",
    },
  ],
};

export const fields = [
  { name: "firstname", type: "string", displayName: "" },
  { name: "lastname", type: "string", displayName: "" },
  { name: "id", type: "id", displayName: "" },
  { name: "shikum", type: "string", displayName: "" },
  { name: "tipul", type: "string", displayName: "" },
  { name: "company", type: "string", displayName: "" },
  { name: "address", type: "string", displayName: "" },
  { name: "phone", type: "phone", displayName: "" },
  { name: "duration", type: "string", displayName: "" },
  { name: "sign", type: "sign", displayName: "" },
  { name: "date", type: "date", displayName: "" },
  { name: "r_fullname", type: "string", displayName: "" },
  { name: "r_id", type: "id", displayName: "" },
  { name: "r_job", type: "string", displayName: "" },
  { name: "r_phone", type: "phone", displayName: "" },
  { name: "r_sign", type: "sign", displayName: "" },
] as const;
